---
title: "R Notebook"
output: html_notebook
---

```{r}
# load packages
library(tidyverse)
library(rstudioapi)
library(lubridate)
library(arules)
library(arulesViz)

# set working directory
setwd(dirname(getActiveDocumentContext()$path))
# load the data
data <- read_delim("data/final/data_clean.csv", delim = ",")

data <- data %>% 
  mutate(gain = str_replace(gain, ",", "."),
         gain = as.numeric(gain)) %>% 
  mutate(birthday = dmy(birthday))
```

# extracting information

```{r}
# extract hour from the bed time answer
data <- data %>% 
  mutate(Timestamp = mdy_hms(Timestamp)) %>% 
  mutate(bed_time = hms(bed_time),
         bed_hour = hour(bed_time),
         bed_minutes = minute(bed_time)) %>% 
  mutate(hour_survey = hour(Timestamp))

```

# creating extra variables 

```{r}
# time they went to sleep
extra_var <- data %>% 
  mutate(went_to_bed = case_when(
    bed_hour >= 19 & bed_hour <=21 ~ "early",
    (bed_hour > 21 & bed_hour <=24) | (bed_hour >= 0 & bed_hour <=1)  ~ "normal",
    bed_hour > 1 & bed_hour <=5 ~ "late",
    is.na(bed_hour) ~ "NA",
    TRUE ~ "Other"
  )) %>% 
  # week day of the form
  mutate(weekday = as.factor(wday(Timestamp, week_start = 1))) %>% 
  # stress level
  mutate(stress_level = case_when(
    stress >= 0 & stress <=33 ~ "low",
    (stress > 33 & stress <=66) ~ "mid",
    stress > 66 & stress <=100 ~ "high",
    is.na(stress) ~ "NA",
    TRUE ~ "Other"
  )) %>% 
  mutate(before_lecture = Timestamp < "2021-03-30 13:30:00") %>% 
  mutate(birthday_wday = wday(birthday, week_start = getOption("lubridate.week.start", 1)))

```

# filled in form before or after the lecture?

```{r}
extra_var %>% 
  group_by(before_lecture, gender) %>% 
  summarise(n = n()) %>% 
  group_by(gender) %>% 
  mutate(n_gender = sum(n)) %>% 
  ungroup() %>% 
  mutate(percent = n/n_gender * 100)
```

#Birthday exploration

```{r}
filtred <- extra_var %>% 
  filter(!is.na(birthday),
         gender != "unknown")

# most common birthday weekday?

filtred %>% 
  group_by(birthday_wday) %>% 
  summarise(n = n()) %>% 
  mutate(n_all = sum(n),
         percent = n/n_all)

# is there a difference between birtday weekday and gender?

filtred %>% 
  group_by(birthday_wday, gender) %>% 
  summarise(n = n())  %>% 
  group_by(gender) %>%
  mutate(n_gender = sum(n)) %>% 
  ungroup() %>% 
  mutate(percent = n/n_gender * 100)

# are there people sharing the same birhtday

share <- filtred %>% 
  group_by(birthday) %>% 
  count() %>% 
  arrange(-n)

share_1 <- share %>% 
  filter(n > 1)

sum(share_1$n)
```

```{r}
sum(share_1$n)
```


# Association rules

```{r}
dataset_courses <- extra_var %>%
  select(program, ml, ir, stats, db, gender, chocolate, went_to_bed, weekday, stress_level) %>% 
  mutate_all(as.factor)
transactions <- as(dataset_courses, "transactions")

# apply algorithm

rule_1 = apriori(data = transactions, 
                        parameter = list(support = 0.02, 
                                         confidence = 0.5))
```

```{r}
inspect(head(sort(rule_1, by = "confidence"), 5))
```






