---
title: "R Notebook"
output: html_notebook
---

```{r}
# load packages
library(tidyverse)
library(rstudioapi)
library(lubridate)

# set working directory
setwd(dirname(getActiveDocumentContext()$path))
# load the data
data <- read_csv("data/ODI-2021.csv")

# rename column and make it upper
data <- data %>% 
  rename(program = `What programme are you in?`) %>% 
  mutate(id = row_number()) %>% 
  mutate(program = toupper(program))
```

# Cleaning the programs columns

## Grouping the programs

```{r}
# group the data by the program name to see biggest groups
grouped <- data %>% 
  group_by(`program`) %>% 
  summarise(n = n()) %>%
  arrange(-n)

head(grouped)
```

## Cleaning the program names

```{r}
### clean artificial inteligence

# check if looking for AI is a good idea
check <- data %>% 
  mutate(detect_ai = str_detect(program, "AI")) %>% 
  select(program, detect_ai)

only_program <- data %>% 
  select(id, program)

clean <- only_program %>% 
  mutate(clean_program = case_when(
    str_detect(program, "AI") ~ "ARTIFICIAL INTELLIGENCE",
    str_detect(program, "ARTIFICIAL INTEL") ~ "ARTIFICIAL INTELLIGENCE",
    program == "CS" ~ "COMPUTER SCIENCE",
    str_detect(program, "BIG DATA") ~ "COMPUTER SCIENCE",
    program == "BA" ~ "BUSINESS ANALYTICS",
    str_detect(program, "ECONOMETRICS") ~ "ECONOMETRICS",
    str_detect(program, "BIOINFORMATICS") ~ "BIOINFORMATICS",
    str_detect(program, "COMPUTATIONAL SCIENCE") ~ "COMPUTATIONAL SCIENCE",
    program == "CLS" ~ "COMPUTATIONAL SCIENCE",
    str_detect(program, "QRM") ~ "QUANTITATIVE RISK MANAGEMENT",
    str_detect(program, "QUANTATIVE RISK MANAGEMENT") ~ "QUANTITATIVE RISK MANAGEMENT",
    program == "BIOINFROMATICS" ~ "BIOINFORMATICS",
    str_detect(program, "INFORMATION SCIENCE") ~ "INFORMATION SCIENCES",
    str_detect(program, "DATA SCIENCE") ~ "DATA SCIENCE",
    str_detect(program, "INFORMATION STUDIES") ~ "DATA SCIENCE",
    str_detect(program, "FINANCE & TECHNOLOGY") ~ "FINANCE AND TECHNOLOGY",
    str_detect(program, "FINANCE AND TECHNOLOGY") ~ "FINANCE AND TECHNOLOGY",
    str_detect(program, "F&T") ~ "FINANCE AND TECHNOLOGY",
    str_detect(program, "FINTECH") ~ "FINANCE AND TECHNOLOGY",
    str_detect(program, "HUMAN LANGUAGE TECHNOLOGY") ~ "HUMAN LANGUAGE TECHNOLOGY",
    program == "HLT" ~ "HUMAN LANGUAGE TECHNOLOGY",
    str_detect(program, "LINGUISTICS") ~ "LINGUISTICS",
    str_detect(program, "E&OR") | str_detect(program, "EOR") ~ "ECONOMETRICS",
    str_detect(program, "BUSINESS ANALYTICS") ~ "BUSINESS ANALYTICS",
    program == "EDS" ~ "ECONOMETRICS",
    str_detect(program, "FINANCE") ~ "FINANCE",
    str_detect(program, "COMPUTER SCIENCE") ~ "COMPUTER SCIENCE",
    program %in% c("DMT", "HTTPS://FORMS.GLE/ETY4NES3KHRQPTMLA", "JE ZUSJE",
                   "OR", "PYTHON") ~ NA_character_,
    TRUE ~ program
  )) %>% 
  select(id, clean_program)

grouped <- clean %>% 
  group_by(`clean_program`) %>% 
  summarise(n = n()) %>%
  arrange(-n)

head(grouped)
```


```{r}
# save cleaned data
write_csv(clean, "data/cleaned_programs.csv")
```
